### ISSUE TITLE
Add ENS Registry to each chain

### ISSUE THREAD

**Issue by fmrsabino** [gnosis/safe-config-service#119]
In case the ENS registry is present on the Chain, then its address should be returned:

```javascript
GET /api/v1/chains/

{
  ...
  "ensRegistryAddress": "<checksummed-address>" // optional
}
```

@gnosis/safe-android @gnosis/safe-ios @gnosis/safe-web

**Comment by fmrsabino** [comment]
@gnosis/safe-android @gnosis/safe-ios @gnosis/safe-web 

Similarly to #125 can you comment here what is required by each of the frameworks used on the client side?

**Comment by fmrsabino** [comment]
According to @gnosis/safe-android and @gnosis/safe-ios we are using a custom solution on the mobile clients which requires the `ensRegistryAddress` (right now hardcoded).

@gnosis/safe-web is `ensRegistryAddress` sufficient for the feature to work on your side?

**Comment by katspaugh** [comment]
In safe-react, we're using `web3.eth.ens.getAddress`.

Currently, we're not overriding the resolver address but it's possible using [`web3.eth.ens.registryAddress`](https://github.com/ChainSafe/web3.js/blob/1.x/docs/web3-eth-ens.rst#registryaddress).

So the proposed solution will work.
