### ISSUE TITLE
Add deployment to dockerhub from Github Actions

### ISSUE THREAD

**Issue by Uxio0** [gnosis/safe-config-service#12]
- [x] Create project `safe-config-service` on dockerhub (Uxío)
- [x] Configure environment variables `DOCKER_USER` and `DOCKER_PASSWORD` (Uxío)
- [x] Configure deployment. Take a look on https://github.com/gnosis/safe-transaction-service
- [x] Prepare deployment doc with @jpalvarezl

**Comment by Uxio0** [comment]
Dockerhub configuration is ready

**Comment by Uxio0** [comment]
You should add `python manage.py check` to the CI too, to check that Django does not complain about the code

**Comment by fmrsabino** [comment]
Thanks Uxio! Will close this ticket then! Thanks for all the help 🙌
