### ISSUE TITLE
Use a generated unique id to represent a safe-app instead of a URL

### ISSUE THREAD

**Issue by fmrsabino** [gnosis/safe-config-service#121]
Using the URL as a unique identifier for the safe-app is error prone as the same app can be represented in multiple forms (eg.: `https://example.com`, `https://example.com/`, `https://example.com/?`, `https://example.com/#` etc... 

We should then generate a unique identifier to represent each app instead of relying on the uniqueness of the url.

```javascript
GET /api/v1/safe-apps/

[
  {
    "id": <stringified-id>,
    ...
  }
]
```

**Comment by Uxio0** [comment]
Sounds good, normalizing an url is not an easy task as there are a lot of edge cases
