### ISSUE TITLE
Add Unstoppable Domains Registry to each chain

### ISSUE THREAD

**Issue by fmrsabino** [gnosis/safe-config-service#125]
In case the Unstoppable Domains registry is present on the Chain, then its address should be returned:

```
GET /api/v1/chains/

{
  ...
  "unstoppableDomainsRegistryAddress": "<checksummed-address>" // optional
}
```

### Update on the payload: https://github.com/gnosis/safe-config-service/issues/125#issuecomment-870687616 

@gnosis/safe-android @gnosis/safe-ios @gnosis/safe-web

**Comment by sche** [comment]
on iOS we use a lib that has hardcoded values of domains registry address https://github.com/unstoppabledomains/resolution-swift/blob/master/Sources/UnstoppableDomainsResolution/Resources/CNS/network-config.json
The library needs network id and rpc url - we have both of them already.

We could check if the network is supported for the library we use and act based on this.
For Android we need to clarify if this parameter is needed.

**Comment by katspaugh** [comment]
Same here, we use UD's own package and [it just take the RPC URL](https://github.com/gnosis/safe-react/blob/main/src/logic/wallets/utils/unstoppableDomains.ts#L11).

**Comment by biafra23** [comment]
On Android we pas the Network and the Infura API-Key

**Comment by fmrsabino** [comment]
> On Android we pass the Network and the Infura API-Key

With "Network" do you mean the network/chain id? And with the "API-Key" do you mean the RPC url?

**Comment by biafra23** [comment]
Network is a type. But selection via chain id is possible. And API_key refers to an Infura API key. Not a url.

**Comment by fmrsabino** [comment]
> @fmrsabino Network is a type. But [selection via chain id](https://github.com/unstoppabledomains/resolution-java/blob/master/src/main/java/com/unstoppabledomains/config/network/model/Network.java#L18) is possible. And API_key refers to an Infura API key. Not a url.

@biafra23 It's not  guaranteed that the RPC will be under Infura so

https://github.com/gnosis/safe-android/blob/278ef94f668583f99ac632472aeac57a54a98b0d/app/src/main/java/io/gnosis/safe/di/modules/RepositoryModule.kt#L77-L80

can probably be changed to

```kotlin
Resolution.builder()
  .providerUrl(NamingServiceType.CNS, "https://rinkeby.infura.io/v3/e0c0cb9d12c440a29379df066de587e6")
  .build();
```

correct?

**Comment by fmrsabino** [comment]
So it seems that the requirements are as follow:

- Web – `rpcUrl`
- iOS – `rpcUrl` + `chainId`
- Android – `rpcUrl` + `chainId`

Given that this information is already provided by the `/chains` endpoint what do you think about the following payload:

```javascript
GET /api/v1/chains/

{
  ...
  "unstoppableDomainsAvailable": <boolean> // required 
}
```

This field would be set manually depending on the availability of the feature on each chain via the admin interface. If it's `True` you can assue that the feature is available and can be used using the data provided already by the endpoint.

My concern with this approach is that it assumes feature parity between the frameworks that each client uses. Eg.: the feature is available on network `X` (deployed) but `X` is not yet part of the Android framework but it is available on Web and iOS. 

@katspaugh @biafra23 @sche

**Comment by katspaugh** [comment]
We currently toggle both ENS and UD together using a static feature toggle in each of the [network configs](https://github.com/gnosis/safe-react/blob/dev/src/config/networks/xdai.ts#L56).

So if we move these configs to the config service, `unstoppableDomainsEnabled` makes total sense.

**Comment by fmrsabino** [comment]
@gnosis/safe-ios and @gnosis/safe-android mentioned that what would make more sense for them is to try to initialise the UD framework given the current chain info that they already have.

So in practical terms, no extra fields would be required for this feature at least on a first iteration. What do you think @gnosis/safe-web ?

**Comment by fmrsabino** [comment]
Since all the clients can use the information already provided by the `/chains` endpoint I will close down this issue.
