### ISSUE TITLE
`ChainInfo` to include minimum recommended `MasterCopy` version

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-config-service#148]
In order to provide information for the clients whether a safe is "Up to date" we need to know which is the version of the master copy that, as a minimum, is recommended.

This information can change from chain to chain, therefore we would like to have a field that specifies the version in the `ChainInfo` object.

```
ChainInfo {
  "minMasterCopyVersion" : "<semver-str>"
}
```

**Comment by jpalvarezl** [comment]
Maybe `minImplementationVersion` would be more appropriate? Doesn't matter to much, as this isn't exposed to the clients anyway.

We should probably implement this first: https://github.com/gnosis/safe-client-gateway/issues/451 in the CGW, so that we can hide the version an expose just the enum.

**Comment by fmrsabino** [comment]
@jpalvarezl So this field would represent the minimum recommended version right?

If we have two recommended versions we only set the lowest on this field. This is just to consider the field name (if it could be `recommendedMasterCopyVersion`)
