### ISSUE TITLE
Support for fixed gas price without oracle

### ISSUE THREAD

**Issue by fmrsabino** [gnosis/safe-config-service#154]
For some chains a fixed gas price can be used (instead of relying on a gas price oracle).

On the safe-react, the `GasPrice` can be either given with `gasPrice | gasPriceOracle?` or `gasPrice? | gasPriceOracle`: 
https://github.com/gnosis/safe-react/blob/ae206843c86aa1663ca6db66d3662c1882d36991/src/config/networks/network.d.ts#L80-L89

Given this, if `gasPrice` is given then `gasPriceOracle` should be `null` and if `gasPriceOracle` is given then `gasPrice` should be null.

### Open Questions

1. Is the `gasPrice` considered to be in `gwei`
2. Is it correct to assume that only one can be provided and not both?

cc/ @gnosis/safe-web

**Comment by dasanra** [comment]
@fmrsabino with that typing in Javascript if one of the values is provided the other one doesn't have to, but still it enforces that at least one of them is set.

Right now I think we are using it only on xDai, so with the current case, the fixed gas price is set to 1Gwei, and we set it in Gwei.

The app globally is mostly expecting that the oracles return the price in Gwei and then convert as necessary

**Comment by rmeissner** [comment]
@dasanra looking at https://github.com/gnosis/safe-react/blob/ae206843c86aa1663ca6db66d3662c1882d36991/src/config/networks/xdai.ts#L9 you set `gasPrice` in Wei (as 1_000_000_000 Wei are 1 Gwei and 1_000_000_000 Gwei would be 1 ETH and I assume the gas price is not 1 eth

**Comment by fmrsabino** [comment]
So if you get the following from the services it'd work for you?

```javascript
{
  ...
  "gasPriceOracle": {
    ...
  },
  "gasPrice": null
}
```

or

```javascript
{
  ...
  "gasPriceOracle": null,
  "gasPrice": <stringified-number>
}
```

**Comment by rmeissner** [comment]
Wouldn't it make sense to use a polymorphic response here? This would clearly show that it is either or and cannot be both. At least on client gateway side this is what is being done in such cases.

e.g. 
```json
{
  "type": "oracle",
  "url": <url_string>,
  "param": <param_name>,
  "multiplier": <multiplier_number>
}

{
  "type": "fixed",
  "gasPrice": <number_string>
}
```

**Comment by fmrsabino** [comment]
Yes I agree. That'd would be a better alternative 👍 Just to put it in context of a `gasPrice` object:

```javascript
{
  "gasPrice" {
    "type": "oracle",
    "url": <url_string>,
    "gasParameter": <param_name>,
    "gweiFactor": <multiplier_number>
  }
}
```

or

```javascript
{
  "gasPrice" {
    "type": "fixed",
    "value": <stringified-number>
  }
}
```

**Comment by fmrsabino** [comment]
> @dasanra looking at https://github.com/gnosis/safe-react/blob/ae206843c86aa1663ca6db66d3662c1882d36991/src/config/networks/xdai.ts#L9 you set `gasPrice` in Wei (as 1_000_000_000 Wei are 1 Gwei and 1_000_000_000 Gwei would be 1 ETH and I assume the gas price is not 1 ETH)

If it is indeed in `Wei` then I think that would be preferable for representation purposes (one `UInt256` instead of a decimal field)

**Comment by dasanra** [comment]
> @dasanra looking at https://github.com/gnosis/safe-react/blob/ae206843c86aa1663ca6db66d3662c1882d36991/src/config/networks/xdai.ts#L9 you set `gasPrice` in Wei (as 1_000_000_000 Wei are 1 Gwei and 1_000_000_000 Gwei would be 1 ETH and I assume the gas price is not 1 ETH)

:facepalm: wrong thing talking without checking. On my memory the number on xDai config file seemed very short, but we were using scientific notation. Sorry about that.

Yes, fixed gas price is using Wei
