### ISSUE TITLE
Support for non-authenticated RPC urls

### ISSUE THREAD

**Issue by fmrsabino** [gnosis/safe-config-service#171]
Currently the RPC url being used assumes that Infura is the provider. Under this assumption, the clients just append the Infura project ID to use that RPC url.

Given that there might be chains not available on Infura and that might not require authentication we can have two different types:

```javascript
GET /api/v1/chains/<chain-id>

{
  "rpcUri": {
    "type": <string>, // INFURA | OTHER
    "value": <url> 
  }
}
```

Other types can be added in the future.

cc/ @gnosis/safe-android @gnosis/safe-ios @gnosis/safe-web 

### Payload Update 1 https://github.com/gnosis/safe-config-service/issues/171#issuecomment-884099079

**Comment by fmrsabino** [comment]
@mikheevm if the team is aligned on this, this might change your proposal on #169

**Comment by sche** [comment]
So on clients, we agree that we try to use rpcUri as is (without appending `project id` or another secret key) for unknown types

**Comment by DmitryBespalov** [comment]
@sche yes, in the future it is possible there could be resources that need other authentication mechanisms, such as http headers. In that case, we'll need to extend this in the future.

@fmrsabino I'd change the enum name from INFURA to API_KEY_PATH to indicate that the api key needs to be appended as a path component to the URL.

We can get inspiration in the future from the https://swagger.io/docs/specification/authentication/

**Comment by fmrsabino** [comment]
@DmitryBespalov @sche 

I think that we can maybe even more explicit and not have the `OTHER` as an option. I also changed from `type` to `authentication`

```javascript
GET /api/v1/chains/<chain-id>

{
  "rpcUri": {
    "authentication": <string>, // API_KEY_PATH | NO_AUTHENTICATION
    "value": <url> 
  }
}

```

or

```javascript
GET /api/v1/chains/<chain-id>

{
  "rpcUri": {
    "authentication": <string>, // eg.: API_KEY_PATH  or null (optional field)
    "value": <url> 
  }
}

```

**Comment by DmitryBespalov** [comment]
@fmrsabino I like the first option with both fields required

**Comment by fmrsabino** [comment]
> @fmrsabino I like the first option with both fields required

@gnosis/safe-android @gnosis/safe-ios @gnosis/safe-web we'll go with the following if there are no further concerns:

```javascript
GET /api/v1/chains/<chain-id>
{
  "rpcUri": {
    "authentication": <string>, // API_KEY_PATH | NO_AUTHENTICATION
    "value": <url> 
  }
}
```

**Comment by mikheevm** [comment]
> #169

cool, I'll adjust my PR once this ticket is addressed
