### ISSUE TITLE
Register CGW hook in order to invalidate its cache

### ISSUE THREAD

**Issue by fmrsabino** [gnosis/safe-config-service#173]
A service hook should be implemented so that when Chain related data is updated, the CGW is notified about those changes and invalidates its cache

**Comment by jpalvarezl** [comment]
## Context

As for the CGW side of things, we technically already expose an endpoint through which chain information can be invalidated. Technically, this would invalidate anything `config` service related (the invalidation pattern only looks for the base URL of the given config service env)

## Resources

`POST /v1/flush/<token>` where `token` is the webhook token of the CGW instance

The body of the request in json:

```json
{
    "invalidate": "Chains"
}
```
