### ISSUE TITLE
Missprint in the blockExplorerUriTemplate: address for xDai on prod

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-config-service#186]
xDai:
https://safe-client.gnosis.io/v1/chains/100/
{"address":"https://blockscout.com/xdai/mainnet/adddress/{{address}}/transactions"

"adddress" instead of "address", as a result,the issue on the mobile client with opening addresses in the blockexplorer (404)

Rinkeby:

add valid URL  with address"blockExplorerUriTemplate":{"address":"https://rinkeby.etherscan.io/"  and "txHash"
Current result for mobile client: https://rinkeby.etherscan.io/ is opened instead of https://rinkeby.etherscan.io/address/0x1230B3d59858296A31053C1b8562Ecf89A2f888b for any safe address

**Comment by fmrsabino** [comment]
> xDai:
> https://safe-client.gnosis.io/v1/chains/100/
> {"address":"[https://blockscout.com/xdai/mainnet/adddress/{{address}}/transactions](https://blockscout.com/xdai/mainnet/adddress/%7B%7Baddress%7D%7D/transactions)"
> 
> "adddress" instead of "address", as a result,the issue on the mobile client with opening addresses in the blockexplorer (404)
> 
> Rinkeby:
> 
> add valid URL with address"blockExplorerUriTemplate":{"address":"https://rinkeby.etherscan.io/" and "txHash"
> Current result for mobile client: https://rinkeby.etherscan.io/ is opened instead of https://rinkeby.etherscan.io/address/0x1230B3d59858296A31053C1b8562Ecf89A2f888b for any safe address

Fixed.

For xDai: https://safe-config.gnosis.io/api/v1/chains/100/
For Rinkeby: https://safe-config.gnosis.io/api/v1/chains/4/
