### ISSUE TITLE
Add pre-commit hook for formatting code with Black

### ISSUE THREAD

**Issue by fmrsabino** [gnosis/safe-config-service#19]
We can add an optional pre-commit hook so that Black runs on each commit: https://black.readthedocs.io/en/stable/version_control_integration.html

**Comment by Uxio0** [comment]
> We can add an optional pre-commit hook so that Black runs on each commit: https://black.readthedocs.io/en/stable/version_control_integration.html

Nice, looks like they recommend that tool also. You can also add `flake8` test so you cannot commit if `flake8` does not pass

**Comment by fmrsabino** [comment]
Opened the PR here: #20

> You can also add `flake8` test so you cannot commit if `flake8` does not pass

`flake8` is running as part of the CI here:

https://github.com/gnosis/safe-config-service/blob/1eaeb7dff33f046717028f1d3409228acd2f1dcb/run#L65

> and also run `isort` before commits

Regarding this part, shall we include `isort` while having `Black`? It seems that they do have different opinions on how sorting is done: https://black.readthedocs.io/en/stable/compatible_configs.html#isort

**Comment by Uxio0** [comment]
> Regarding this part, shall we include isort while having Black? It seems that they do have different opinions on how sorting is done: https://black.readthedocs.io/en/stable/compatible_configs.html#isort

I would like to have both, as I found really useful the `isort` sorting of dependencies depending on the project (e.g. PROJECT LIBRARIES, FIRST PARTY, THIRD PARTY, core libraries...) 

https://pycqa.github.io/isort/docs/configuration/black_compatibility/
