### ISSUE TITLE
Stringify `id` and `chainIds` fields in `/safe-app` endpoint

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-config-service#215]
## Context

Currently the service's `/safe-app` endpoint returns the following response:

```json
[
  {
    "id": 0,
    "url": "string",
    "name": "string",
    "iconUrl": "string",
    "description": "string",
    "chainIds": [
      0
    ],
    "provider": {
      "url": "string",
      "name": "string"
    }
  }
]
```

## Feature

`chainId`s in generaly are handled as strings in apps and the CGW. The `id` field, to follow the convention could also be made into a string type, like so:

```json
[
  {
    "id": "0",
    "url": "string",
    "name": "string",
    "iconUrl": "string",
    "description": "string",
    "chainIds": [
      "0"
    ],
    "provider": {
      "url": "string",
      "name": "string"
    }
  }
]
```

**Comment by fmrsabino** [comment]
@jpalvarezl I would say that this can be done on the CGW side. Currently we are just following the default serialisation of the `PositiveBigInteger` field (64 bits) and it is represented as an `int` in JSON.

Given that, if the clients want to have it as a `String` I would expose it as such on the CGW and would close this issue what do you think?

**Comment by jpalvarezl** [comment]
Yeah, that sounds good to me. I will adjust the PR accordingly.
