### ISSUE TITLE
Add a description field for each chain

### ISSUE THREAD

**Issue by katspaugh** [gnosis/safe-config-service#216]
In the UI, we'd like to display short descriptions for each network. E.g.

* **name**: Volta
* **description**: Energy Web testnet

Please add a new text field in the chain configs. 256 chars or so would be enough.

**Comment by fmrsabino** [comment]
@katspaugh Regarding the description should it be an optional field?

```javascript
GET /api/v1/chains

{
  "chainName": <string>,
  "description": <string>, // optional
}
```

**Comment by katspaugh** [comment]
It could be an empty string if not set.

**Comment by fmrsabino** [comment]
> It could be an empty string if not set.

Will go with 

```javascript
GET /api/v1/chains

{
  "chainName": <string>,
  "description": <string>, // required but can be empty
  ...
}
```

**Comment by katspaugh** [comment]
@fmrsabino is this on staging? Can you post the GET link?

**Comment by fmrsabino** [comment]
> @fmrsabino is this on staging? Can you post the GET link?

It is. Available here: https://safe-config.staging.gnosisdev.com/api/v1/chains/

**Comment by katspaugh** [comment]
Seems to work but all the descriptions are empty atm. How can I edit it in the admin?
I tried https://safe-config.staging.gnosisdev.com/admin/  but it's only showing the Apps and Providers.

**Comment by fmrsabino** [comment]
> Seems to work but all the descriptions are empty atm. How can I edit it in the admin?
> I tried https://safe-config.staging.gnosisdev.com/admin/ but it's only showing the Apps and Providers.

Descriptions are empty because those are the defaults (descriptions were not set). Can you try editing now?

**Comment by katspaugh** [comment]
Yep, it works. Thanks @fmrsabino! Did you have to enable it somehow for my user? We'll need all the users to have access.

**Comment by fmrsabino** [comment]
> Yep, it works. Thanks @fmrsabino! Did you have to enable it somehow for my user? We'll need all the users to have access.

Yes access was granted to edit chains. Who are all the users?

**Comment by katspaugh** [comment]
Yes, all of them on staging. On Prod, only Dani and me.

**Comment by fmrsabino** [comment]
> Yes, all of them on staging. On Prod, only Dani and me.

Done on `staging` ✅
