### ISSUE TITLE
(WIP) add a new value in the config service setting the root domain of the app where the custom safe app is based

### ISSUE THREAD

**Issue by Graeme-Code** [gnosis/safe-config-service#270]
Background:
We are working on a ticket to alert users when they connect to a Dapp which is avaliable as a Safe App. Please see ticket here for context: https://github.com/gnosis/safe-react-apps/issues/167

Problem:
Many apps still use a custom version hosted on IPFS so we can't do a domain match in order to detect that the app used through wallet connect is an app that already has a proper Safe App. The solution could be to add a new value in the config service setting the root domain of the app where the custom safe app is based.

**Comment by rmeissner** [comment]
not relevant anymore. Reopen if more information is available
