### ISSUE TITLE
Add an `isEip1559Enabled` flag to Chain configs

### ISSUE THREAD

**Issue by katspaugh** [gnosis/safe-config-service#318]
## Overview
We currently have [a client-side config](https://github.com/gnosis/safe-react/blob/589ec5ef5b434716107a3dfda5a05c1036c7f067/src/config/chain-workarounds.ts#L11) chains that support EIP-1559-style transaction params (`maxFeePerGas`).

This should obviously be on the config service.

## Requirements
* Add a boolean field `isEip1559Enabled` to the Chain model
* Set it to true for mainnet, rinkeby and xdai

**Comment by Uxio0** [comment]
Makes sense. I would change the naming for `isEip1559Enabled` (if you agree @katspaugh can you edit it?)

**Comment by fmrsabino** [comment]
Why not use `features` for this one?

**Comment by Uxio0** [comment]
> Why not use `features` for this one?

Forgot about this, sounds way better

**Comment by katspaugh** [comment]
Great idea!

**Comment by fmrsabino** [comment]
I will close down this issue since it can be already tackled via the admin interface 👍
