### ISSUE TITLE
Add `extraGasFactor` to the Chain configs

### ISSUE THREAD

**Issue by katspaugh** [gnosis/safe-config-service#319]
## Overview
Gas limit estimation on networks like Arbitrum and xDai gives a gas limit that is too low.
Tx submits fine but is then reverted by the EVM with `Not enough gas to execute safe transaction`.
[So we add X% of gas on top on the client-side.](https://github.com/gnosis/safe-react/blob/589ec5ef5b434716107a3dfda5a05c1036c7f067/src/config/chain-workarounds.ts#L3-L8)

This parameter should be on the config-service.

## Requirements
* Add a float field `extraGasFactor ` to the Chain model
* Set it to 1.7 for xDai

**Comment by Uxio0** [comment]
This would be easy to implement, but before that I would like to know when it's that happening and if we can do something, if not we are just doing a workaround for an existing (important) bug. We are aware of estimation issues on `xdai` when `nethermind` node is used (config service provides an OpenEthereum rpc and it should be ok).

Regarding `arbitrum` it would be very valuable that you provide a tx estimation that's not working propertly so we can debug it.

If there's nothing we can do about it we will implement this issue.

**Comment by katspaugh** [comment]
I was testing with the same xDai RCP as the config-service. `rpc.xdaichain.com`. See https://github.com/gnosis/safe-react/pull/3018. Txns fail with +60% and less, but succeed with +70%. 🤷 

On Arbitrum, AFAIR, we added the 20% solely for NFT transactions. Normal txns were OK.
I'll test this again and will let you know.

**Comment by Uxio0** [comment]
> I was testing with the same xDai RCP as the config-service. `rpc.xdaichain.com`. See [gnosis/safe-react#3018](https://github.com/gnosis/safe-react/pull/3018). Txns fail with +60% and less, but succeed with +70%. 🤷

That's what's not intended @fmrsabino is changing it.

> On Arbitrum, AFAIR, we added the 20% solely for NFT transactions. Normal txns were OK. I'll test this again and will let you 
know.

👍🏻

**Comment by katspaugh** [comment]
I've tried to send an NFT today but gas estimation is failing completely...

What RPC should we use on the client in the meanwhile?

**Comment by fmrsabino** [comment]
@katspaugh @Uxio0 RPC endpoint has been changed for xDAI: https://safe-config.gnosis.io/api/v1/chains/100/

Please use the one provided here ☝️

**Comment by katspaugh** [comment]
It looks like sending NFTs works fine on Arbitrum without the extra 20%. So I'll remove that.
However, xDai still needs to be overestimated by 70%.

**Comment by Uxio0** [comment]
> It looks like sending NFTs works fine on Arbitrum without the extra 20%. So I'll remove that. However, xDai still needs to be overestimated by 70%.

Can you provide a tx hash so we can debug?

**Comment by katspaugh** [comment]
A tx hash of what?

**Comment by Uxio0** [comment]
I meant xDai, as you say Arbitrum is working now:
> It looks like sending NFTs works fine on Arbitrum without the extra 20%. So I'll remove that.

I was talking about a tx hash of a correct NFT send in xDai 😉

**Comment by katspaugh** [comment]
xDai underestimates in general, not just NFTs. You can try any tx on https://gnosis-safe.io/app/xdai

**Comment by Uxio0** [comment]
@katspaugh I don't have testing xDai, could you provide the Safe you are using?

**Comment by Uxio0** [comment]
What I found out:
- `safeTxGas` is always well estimated using our backend
- `gasLimit` for the tx is not working when using a nethermind node. Tested it with an `OpenEthereum v3.3.0rc15` node and it's working

**Comment by fmrsabino** [comment]
Closing the issue as there's no further action to be done on the `safe-config-service`
