### ISSUE TITLE
Add Avalanche support

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-config-service#321]
Chain Info: https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-43114.json

Deployment PR: https://github.com/gnosis/safe-deployments/pull/19

**Comment by fmrsabino** [comment]
Chain is now available on `staging`: https://safe-config.staging.gnosisdev.com/api/v1/chains/43114/

**Comment by fmrsabino** [comment]
Support was added to staging. Closing the issue.
