### ISSUE TITLE
Add `publicRpcUrl` field in the Chain model

### ISSUE THREAD

**Issue by katspaugh** [gnosis/safe-config-service#324]
When the user connects to a chain for the first time and don't have it configured in their wallet, we offer them to add this chain automatically to the wallet. This is atm supported only by MetaMask.

For this config, we'll need a public RPC URL.

## Requirement
* Add a string field `publicRpcUrl` for Chains
* Populate existing chain configs with recommended public RPCs from the docs

**Comment by fmrsabino** [comment]
After some internal discussion, I suggest the following proposal:

```javascript
GET /api/v2/chains

[
  {
    "chainId": <bigint>,
    "rpcs": [
        "type": <string>, // PUBLIC | SAFE_APPS | CLIENT
        "authentication": <string>, // API_KEY_PATH | NO_AUTHENTICATION
        "value": <string> // rpc url
    ]
  }
]
```

@gnosis/safe-web  @gnosis/safe-services

**Comment by fmrsabino** [comment]
@gnosis/safe-web in order to not create breaking changes I've added a new key to `v1` as per your suggestion in https://github.com/gnosis/safe-config-service/pull/340

Once it is merged you can access it via:

```javascript
GET /api/v1/chains/<chainId>

{
  ...
  "publicRpcUri": {
    "authentication": <string>, // API_KEY_PATH | NO_AUTHENTICATION
    "value": <uri>,
  },
}
```

**Comment by iamacook** [comment]
Thanks @fmrsabino. Funnily enough, I am just this moment having issues with Polygon and needing the public RPC.

**Comment by fmrsabino** [comment]
> Thanks @fmrsabino. Funnily enough, I am just this moment having issues with Polygon and needing the public RPC.

This still needs to be implemented on the Client Gateway but hopefully it will be available on staging today 🙌
