### ISSUE TITLE
Add Optimism networks to staging

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-config-service#332]
Chain Info: https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-10.json

Deployment Issue: https://github.com/gnosis/safe-deployments/issues/29

**Comment by fmrsabino** [comment]
Added: https://safe-client.staging.gnosisdev.com/v1/chains/10

**Comment by katspaugh** [comment]
As per @lukasschor's suggestion:

> Avalanche instead of Avalanche Mainnet
> Optimism instead of Optimistic Ethereum

I'm renaming these names on Django prod.
