### ISSUE TITLE
Safe apps: add a field for different access control types

### ISSUE THREAD

**Issue by mikheevm** [gnosis/safe-config-service#351]
Context: https://github.com/gnosis/safe-react/issues/2672

We need to know if the app restricts access by source (and therefore can't be loaded in the desktop app) to filter such apps.

The field should be an array of accepted origins and NULL if the app doesn't restrict its access.

The field should be
```
access_control: { type: "NO_RESTRICTIONS" }
or
access_control: { type: 'DOMAIN_RESTRICTION', data: [... ] }
```

It should also accept a new query param `host_domain` that accepts an URL and returns apps that can be displayed for this host

- [ ] Implementation
- [ ] Gitbook doc flag update

**Comment by rmeissner** [comment]
Would it make sense to rather have an array of accepted origins?

**Comment by mikheevm** [comment]
the only origin we have is `https://gnosis-safe.io/`, an array may be more future proof if we're going to host multiple interfaces, but I'm not sure if we need it now

**Comment by mikheevm** [comment]
Ok, I took this from 1inch app:
```
content-security-policy: frame-ancestors 'self' https://gnosis-safe.io https://dev.gnosis-safe.io https://ledger-live-platform-apps.vercel.app https://bsc.gnosis-safe.io https://polygon.gnosis-safe.io https://tmm.world https://app.dhedge.org;
```

you're right, will adjust the ticket

**Comment by katspaugh** [comment]
Please don't call it `restrictsAccessTo` though.

`allowedHostList` or `allowedUrl` is better.

**Comment by fmrsabino** [comment]
> We need to know if the app restricts access by source (and therefore can't be loaded in the desktop app) to filter such apps.

So from the client perspective you just want to filter out apps that have `Content Security Policy` enabled?

**Comment by mikheevm** [comment]
> Please don't call it restrictsAccessTo though.

`allowedSources`? frame-ancestors header can also take things other than URL

**Comment by mikheevm** [comment]
> > We need to know if the app restricts access by source (and therefore can't be loaded in the desktop app) to filter such apps.
> 
> So from the client perspective you just want to filter out apps that have `Content Security Policy` enabled?

Content Security Policy is one of the ways app implement it; some of them use hacky conditional `nginx` configs that add necessary headers depending on the origin of the request

**Comment by fmrsabino** [comment]
> > > We need to know if the app restricts access by source (and therefore can't be loaded in the desktop app) to filter such apps.
> > 
> > 
> > So from the client perspective you just want to filter out apps that have `Content Security Policy` enabled?
> 
> Content Security Policy is one of the ways app implement it; some of them use hacky `nginx` configs that add necessary headers depending on the origin of the request

Looking at the original issue it seems that we have distinction between the desktop app and the web app so some `safe-app` can be loaded to one client but not the other.

Wondering if something like `GET /api/v1/safe-apps?client=desktop` would be enough from the client perspective. On the backend side we'd have a collection of client types.

**Comment by mikheevm** [comment]
> > > > We need to know if the app restricts access by source (and therefore can't be loaded in the desktop app) to filter such apps.
> > > 
> > > 
> > > So from the client perspective you just want to filter out apps that have `Content Security Policy` enabled?
> > 
> > 
> > Content Security Policy is one of the ways app implement it; some of them use hacky `nginx` configs that add necessary headers depending on the origin of the request
> 
> Looking at the original issue it seems that we have distinction between the desktop app and the web app so some `safe-app` can be loaded to one client but not the other.
> 
> Wondering if something like `GET /api/v1/safe-apps?client=desktop` would be enough from the client perspective. On the backend side we'd have a collection of client types.

Hmm, but it's about the source and not the client itself. If I fork safe-react I keep the same client but not the source because I can't host it on gnosis-safe.io. Maybe there could be an additional host query param 🤔

**Comment by mikheevm** [comment]
> Would it make sense to rather have an array of accepted origins?

Actually, I misread your message and I don't think that an array of accepted origins makes more sense because most apps don't restrict access by origin and the goal of the flag was to easier recognize such apps on the client.

**Comment by fmrsabino** [comment]
> Hmm, but it's about the source (host) and not the client itself. If I fork safe-react I keep the same client but not the source because I can't host it on gnosis-safe.io. Maybe there could be an additional host query param 🤔

What I meant was that the `safe-apps` that a specific instance of the  `safe-config-service` holds can be seen as tied to a specific domain. Eg.: staging safe-apps being different than production safe-apps.

If someone deploys the `safe-config-service` then they can adjust the apps that actually work in their environment/instances. If there are other work arounds that make the app not work on our side (besides the `content-security-policy`) then that app should not be part of `safe-apps` (unless we need to distinguish between different client types but that can be done without adding a collection of urls)

**Comment by mikheevm** [comment]
> What I meant was that the `safe-apps` that a specific instance of the `safe-config-service` holds can be seen as tied to a specific domain. Eg.: staging safe-apps being different than production safe-apps.
> 
> If someone deploys the `safe-config-service` then they can adjust the apps that actually work in their environment/instances. If there are other work arounds that make the app not work on our side (besides the `content-security-policy`) then that app should not be part of `safe-apps` (unless we need to distinguish between different client types but that can be done without adding a collection of urls)

Sorry, but I lost track. Why do environments matter in this case? The flag was only needed to distinguish apps that restrict iframe loading to safe domains. Most of them do not put any restrictions

**Comment by mikheevm** [comment]
I discussed the issue on slack with @fmrsabino, and we found a compromise solution. I'll work on the ticket
