### ISSUE TITLE
Gas price editable from the Chain model

### ISSUE THREAD

**Issue by katspaugh** [gnosis/safe-config-service#354]
Please make the Gas Price editable directly via Chain configs.
Like we did for Features and Wallets.
Thanks!

**Comment by fmrsabino** [comment]
This is a good idea. Will ping you once it's available.

**Comment by fmrsabino** [comment]
@katspaugh you should be able to easily edit the gas price now from the Chain admin panel on `staging`

**Comment by katspaugh** [comment]
Fantastic, thank you @fmrsabino!
