### ISSUE TITLE
Token logos are too large/heavy

### ISSUE THREAD

**Issue by katspaugh** [gnosis/safe-config-service#373]
**Describe the bug**
I did a spot check on different coin icons we are receiving from the gateway.

https://safe-transaction-assets.gnosis-safe.io/chains/4/currency_logo.png – 3258x3258 px, 161 Kb
https://safe-transaction-assets.gnosis-safe.io/chains/43114/currency_logo.png – 1500x1500, 41 Kb

I suppose many other icons are also unnecessarily big. This is very bad for the page loading speed.

## Frontend requirements
* Token logos should be sufficiently big, so that we can downscale them to different sizes in different components.
* But not too big. 512x512 would be good enough for most situations, including hi-res (aka Retina) screens.
* Images should be optimized, e.g. via OptiPng. This will already halve the current sizes.
 
Try it on optipng.com and there's a CLI util of the same name.

## To summarize
Please do the following:
* Resize all the existing icons to 512x512 px
* If the icon is smaller, keep the current size
* Run them through optipng
* Set up a pipeline to do the same for new icons

## Automated pipeline
Whenever we upload an image, we should programmatically perform the same actions as requested above for existing images.
Namely:
* resize it to 512 px on the largest side (e.g. 512x512, or 300x512, or 512x400 etc)
* if the original is smaller, keep the original size
* optimize using OptiPng

## Why OptiPng
OptiPng is a de-facto standard CLI tool to remove unnecessary kilobytes from PNGs and JPGs.
In most cases, it reduces the size of a file by 100% (i.e. halves the size).
The resource cost is negligible as this will be happening on the upload of a single image.

**Comment by fmrsabino** [comment]
I've implemented a restriction on upload regarding images bigger than 512x512 here https://github.com/gnosis/safe-config-service/pull/374

**Comment by katspaugh** [comment]
Amazing, thank you guys!

**Comment by fmrsabino** [comment]
> Amazing, thank you guys!
> 
> Upd: I'm still seeing https://safe-transaction-assets.gnosis-safe.io/chains/4/currency_logo.png at the 3k resolution. Is it cached?

You should see them all updated now (staging and production). Let us know if you see one that is above 512x512 🙌

**Comment by katspaugh** [comment]
Yep, all good now, thank you! 🙏

**Comment by fmrsabino** [comment]
@katspaugh Do we have a restriction on the web client that the images provided should have the same ratio? (ie.: do you scale them to have the same ratio)

**Comment by katspaugh** [comment]
@fmrsabino no restriction, we scale them using only the height, width is auto.

**Comment by fmrsabino** [comment]
> @fmrsabino no restriction, we scale them using only the height, width is auto.

@jpalvarezl This might answer your question. I'd say that we can move forward without restricting the ratio of the image. We can add the validation if we need it in the future

**Comment by katspaugh** [comment]
#374 doesn't really check the pipeline box.

> Set up a pipeline to do the same for new icons

This implied that all uploaded images should be optimized using optipng.

**Comment by fmrsabino** [comment]
> #374 doesn't really check the pipeline box.
> 
> > Set up a pipeline to do the same for new icons
> 
> This implied that all uploaded images should be optimized using optipng.

This needs to be evaluated. Can you update the ticket description for more reasons why we should use `optipng` – and how resource heavy this tool is.

I will reopen the ticket.

**Comment by katspaugh** [comment]
Added 👍

**Comment by fmrsabino** [comment]
> Added 👍

Thank you. We will discuss this tomorrow in our sync.

**Comment by fmrsabino** [comment]
Discussed in the sync that no further action is required right now on the safe-config-service. Closing the ticket.
