### ISSUE TITLE
Deploy service to staging

### ISSUE THREAD

**Issue by Uxio0** [gnosis/safe-config-service#41]
- [x] Deployment
- [x] Create superuser
- [x] Load initial data
- [x] Test on the clients

**Comment by fmrsabino** [comment]
On the deployment side the variable name for allowed hosts is `DJANGO_ALLOWED_HOSTS` whereas currently in this service the name is `ALLOWED_HOSTS` I will change it as part of this issue to match the variable name in the transaction service.

**Comment by fmrsabino** [comment]
Clients were able to retrieve the data successfully. Closing the issue.
