### ISSUE TITLE
Add a new Gas Price parameter for default maxPriorityGasFee

### ISSUE THREAD

**Issue by katspaugh** [gnosis/safe-config-service#417]
## Context
In https://github.com/gnosis/safe-react/issues/3185, we've added an option for the user to edit the `maxPriorityGasFee`.

Previously, we weren't sending it from the app, and it was set to a fixed value of 2.5 Gwei by web3.js under the hood.
Now, it's editable by the user, but we're still using the hardcoded value of 2.5 Gwei as the default.

## Problem
On Polygon, 2.5 Gwei is too high (according to MM).

## Proposal
It would be nice to set a default value per chain in the Config Service. Please add a new field in wei, similar to the Fixed Gas Price, called `maxPriorityGasFee`.

### Requirements
* Name: `maxPriorityGasFee`
* Desc: **Max priority fee (wei)**
* The field should be nullable

**Comment by fmrsabino** [comment]
@katspaugh should this issue be closed in favour of https://github.com/gnosis/safe-react/issues/3393?

**Comment by katspaugh** [comment]
Yes, let's close it @fmrsabino 👍
