### ISSUE TITLE
Add information about creating a user for the admin panel and OTP

### ISSUE THREAD

**Issue by Uxio0** [gnosis/safe-config-service#439]
I've got some questions about how to use the admin panel in the config service, and also how to enable/disable OTP. It would be good to have it on the `README` and on https://github.com/gnosis/safe-infrastructure#step-2-setup-djando-superusers

**Comment by fmrsabino** [comment]
Section 1 of the README is all about configuration. Each configuration is documented under https://github.com/gnosis/safe-config-service/blob/main/.env.example

**Comment by Uxio0** [comment]
> Section 1 of the README is all about configuration. Each configuration is documented under https://github.com/gnosis/safe-config-service/blob/main/.env.example

Agree, but users don't need to know how Django works, how to create users or where the admin panel is

**Comment by fmrsabino** [comment]
> > Section 1 of the README is all about configuration. Each configuration is documented under https://github.com/gnosis/safe-config-service/blob/main/.env.example
> 
> Agree, but users don't need to know how Django works, how to create users or where the admin panel is

For creating an admin and where the admin panel is I think we can describe in the README how to do it. But if someone maintains a Django service they should know how it works.

**Comment by Uxio0** [comment]
> For creating an admin and where the admin panel is I think we can describe in the README how to do it. But if someone maintains a Django service they should know how it works.

I agree they should get some knowledge for maintaining the service. But I don't think they should go through the Django documentation to bootstrap the service and set up a chain.

Personally I host a lot of services in my home server and they run in multiple languages/frameworks that I don't even know, and I only search for docs when something is not working as it should, but for daily usage I expect easy set up instructions.

**Comment by rmeissner** [comment]
Hmm I don't have a super strong opinion on the general topic. My only comment related to the specific case is, that the default env file enables 2fa and therefore I would also mention it in the readme how to set it up. If we disable it by default, then I think it is enough to mention the details in the env file documentation.

**Comment by Uxio0** [comment]
> And for me it is ok if certain options in the env file can only be used if you have some knowledge around the framework that is used

I agree on this. But for something that should be used when setting up the service, I think we should document it (creating an user and accessing the admin panel). If not, we will keep getting questions for people about how to access the admin interface

**Comment by jpalvarezl** [comment]
I am trying to setup this using the `docker-compose.yml` file in the `safe-infrastructure` repository, which like @Uxio0 mentions, should be a quick guide on how to bootstrap the services. 
I don't think it is a fair assumptions that the users of our services will be "maintainers" of the service. Sometimes you want to simply run the services pointing to a node that it is not the ones we use, that doesn't mean you will deploy a production ready instance and be willing to take the cost of maintaining it.

**Comment by fmrsabino** [comment]
> I am trying to setup this using the docker-compose.yml file in the safe-infrastructure repository, which like @Uxio0 mentions, should be a quick guide on how to bootstrap the services.
I don't think it is a fair assumption that the users of our services will be maintainers of the service. Sometimes you want to simply run the services pointing to a node that it is not the ones we use, that doesn't mean you will deploy a production ready instance and be willing to take the cost of maintaining it.

> I would therefore be of the opinion for the default to be not having 2FA enabled.

We need to clarify if this is first for Gnosis or if it's for external users that might not even need to run this in production.

If it's for Gnosis then by default the configuration that we have in the config-service is for production deployments. Reason is that deployment to production should require minimal configuration. If one is developing with the service they can fine-tune the configuration under `.env` as it's already explained in the `README`.

At the moment we consider that the deployment is targeted for Gnosis thus 2FA is enabled.

I agree that we can explain better how to create an admin and disable 2FA in the `README`. 

Additionally we should keep in mind that 2FA is not the only configuration available and explaining each option might be too much for the `README` file (we might need an alternative here. The current one is the `.env` file documentation itself).

**Comment by Uxio0** [comment]
> We need to clarify if this is first for Gnosis or if it's for external users that might not even need to run this in production.

I think this repo was always for external users wanting to run our services in an easy way.

In my opinion this repo should go on the line that making it work for users first, and not for our own infra (we are not using it anyway, maybe just for local dev)

**Comment by Uxio0** [comment]
From my opinion having a lot of defaults that fit Gnosis is really good and we should do it, but we need to think in another people using the service, and that's way some extra things should not be enabled by default. For example, in the `safe-transaction` repo `SSO` is not enabled by default and should be enabled on the deployment configuration or via environment variables
