### ISSUE TITLE
Add tag support to Safe Apps

### ISSUE THREAD

**Issue by fmrsabino** [gnosis/safe-config-service#486]
Tags are being introduced in order to provide more context for each Safe App.

Currently all Safe Apps are part of the same "category" ie.: there's no way to group or label Safe Apps.

Labelling Safe Apps has the following advantages:
- Provides filtering capabilities on a specific label (eg.: DeFi apps)
- Can be used to promote some apps (eg.: a promoted group)
- Can be used to distinguish official apps from not official ones

## API
```javascript
GET /api/v1/safe-apps

{
    "id": 1,
    "name": "OpenZeppelin",
    "tags": [
	    "tag1",
	    "tag2",
	    "tag3"
    ]
    ...
}
```

- An app can have multiple `tags`
- `tags` can be empty but never `null`
- A `tag` can be part of multiple apps

**Comment by fmrsabino** [comment]
@gnosis/safe-web what do you think about the proposed specification?

**Comment by katspaugh** [comment]
Looks great!

I like that you wrote they should always be an array even if empty.

**Comment by fmrsabino** [comment]
@gnosis/safe-web Is there any kind of sorting that needs to be applied to the tags? Or maybe an admin-set ranking for each tag?

**Comment by katspaugh** [comment]
Don’t think so.

**Comment by fmrsabino** [comment]
@katspaugh @DiogoSoaress can a `tag` have whitespace?

**Comment by katspaugh** [comment]
@fmrsabino I'd say let's keep it simple and not add any restrictions on them.

This line of thinking will keep us from going in the direction of "are tags just strings, or are they a model with id and title".

**Comment by fmrsabino** [comment]
> @fmrsabino I'd say let's keep it simple and not add any restrictions on them.
> 
> This line of thinking will keep us from going in the direction of "are tags just strings, or are they a model with id and title".

PR is open with the current requirements. I will let you know once it hits `staging`.

**Comment by fmrsabino** [comment]
@gnosis/safe-web Tags are now available on `staging`
