### ISSUE TITLE
Add theme information to the chain endpoint

### ISSUE THREAD

**Issue by fmrsabino** [gnosis/safe-config-service#86]
Frontend clients have a theming option for each L2 chain. This information should be stored and retrieved with `/api/v1/chains` so that clients can render the respective theme for each chain.

The following should be added to the `/api/v1/chains` endpoint.

### Initial proposal:

```javascript
{
  ...
  "theme": {
       "light": {
           "textColor": <hex-color-string>,
           "backgroundColor": <hex-color-string>
       },
       "dark": {
           "textColor": <hex-color-string>,
           "backgroundColor": <hex-color-string>
       }
   }
}
```

### Update on the payload: https://github.com/gnosis/safe-config-service/issues/86#issuecomment-862340184

**Comment by tschubotz** [comment]
The text <> background color differentiation make sense since some require a black-ish text, other white-ish.
The colors are selected depending on the branding of the respective network.  Hence I'm not so sure whether we really need to differentiate between light and dark theme. What I mean is e.g. Optimism will have this red color either way (https://optimism.io/), no matter if in light or dark color.

cc @elgatovital did you think about this already by any chance?

**Comment by elgatovital** [comment]
I don't think this is a good idea. Styling and theming should be done locally. I am also against having different colors for different L2 networks. It seems now that we are taking not so subtle indication approach and thus colors and styles of the network indicator should not bite with the rest of the design.

**Comment by fmrsabino** [comment]
>  Hence I'm not so sure whether we really need to differentiate between light and dark theme. What I mean is e.g. Optimism will have this red color either way (https://optimism.io/), no matter if in light or dark color.

So this means that for the clients that support light/dark mode these network colours should not change correct?

**Comment by tschubotz** [comment]
> So this means that for the clients that support light/dark mode these network colours should not change correct?

Yes, in my opinion there is no point in using different colors for light vs. dark currently. Perhaps later.

I think though that each network should have a background color and a separate text color. That's how we design it currently on mobile and web. On some colors, a bright text color is needed. On other a darker one.

**Comment by fmrsabino** [comment]
> > So this means that for the clients that support light/dark mode these network colours should not change correct?
> 
> Yes, in my opinion there is no point in using different colors for light vs. dark currently. Perhaps later.
> 
> I think though that each network should have a background color and a separate text color. That's how we design it currently on mobile and web. On some colors, a bright text color is needed. On other a darker one.

I see. So following your suggestion I would simplify it further while leaving the text color and background color available as separate fields:

```javascript
"theme": {
    "textColor": <hex-color-string>,
    "backgroundColor": <hex-color-string>
}
```

**Comment by jpalvarezl** [comment]
Maybe it would be better to return an array rather than an object (so we leave the door open to the possibility of having many themes?

**Comment by fmrsabino** [comment]
> Maybe it would be better to return an array rather than an object (so we leave the door open to the possibility of having many themes?

I'd be conservative in the beginning and leave it as a single object for the `theme` as this is what is expected on every client. Additionally if we have the distinction in the future between dark/light modes it might be easier on the client side to address these themes directly like `theme.light` and `theme.dark` instead of `themes[0]` and `themes[1]`

**Comment by jpalvarezl** [comment]
yeah, I think we would still need an additional field in that case to identify the individual theme. I think by index it would not be very effective, like you mentioned.
