### ISSUE TITLE
Add Gas Price Oracle for each chain

### ISSUE THREAD

**Issue by fmrsabino** [gnosis/safe-config-service#87]
Client should be able to use a gas price oracle that is associated with a specific chain. Given that, the oracle information and parameters should be retrieved with each chain.

```javascript
{
  ...
  "gasPriceOracle": { // optional
       "url": <url-string>,
       "gasParameter": <string> // eg.: safeLow | average | fast
   }
}
```

Open Questions:
1. Do we require that added chains have a Gas Price Oracle?

## Chains
 * **BSC**: api.bscscan.com
 * **Arbitrum**: uses the eth_gasPrice RPC method

**Comment by rmeissner** [comment]
We decided against having this in the core services. 

@Uxio0 if I misunderstood feel free to reopen

**Comment by fmrsabino** [comment]
I would say that the `gasParameter` can be `null` even if we have a `url` but not the other way around. Thoughts? @rmeissner @katspaugh

**Comment by fmrsabino** [comment]
@gnosis/safe-web Do you require any additional parameter for the Gas Price Oracle? The multiplier was discussed at some point.

**Comment by katspaugh** [comment]
We won't need a multiplier if the new oracle returns a normalized price.

Right now it's needed because each oracle API (like ethgasstation) has a different format.

**Comment by fmrsabino** [comment]
> We won't need a multiplier if the new oracle returns a normalized price.
> 
> Right now it's needed because each oracle API (like ethgasstation) has a different format.

What would be the format that you are expecting. I quickly checked the safe-react app and you have a `gweiFactor` which is a `string` (representing a number).

```javascript
{
  ...
  "gasPriceOracle": { // optional
       "url": <url-string>,
       "gasParameter": <string> // eg.: safeLow | average | fast
       "gweiFactor": <stringified-number> // required – default=1? 
   }
}
```
