### ISSUE TITLE
Use different namespace and endpoint name for `/safe-apps`

### ISSUE THREAD

**Issue by fmrsabino** [gnosis/safe-config-service#89]
The endpoint `/api/v1/safe-apps` is currently under the `v1` namespace and `safe-apps` endpoint name.

To align it better with the future endpoints the following should be changed:

- the namespace changes from `v1` to `safe-apps`
- the endpoint name changes from `safe-apps` to `list`

This results in a reverse url resolution with `safe-apps:list` instead of `v1:safe-apps`

**Comment by Uxio0** [comment]
You can take a look at You can go with url path versioning https://www.django-rest-framework.org/api-guide/versioning/#urlpathversioning
